import type { Metadata } from "next";
import { Bebas_Neue, Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import ClientLayout from "./layout-client";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    weight: [
        "100", // Thin
        "200", // Extra Light
        "300", // Light
        "400", // Regular
        "500", // Medium
        "600", // Semi Bold
        "700", // Bold
        "800", // Extra Bold
        "900", // Black
    ],
    style: ["normal", "italic"],
    subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
    variable: "--font-bebas",
    weight: [
        "400", // Regular
    ],
    style: ["normal"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Maynkudu",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${bebasNeue.variable} transition-colors duration-500 font-poppins tracking-tighter font-medium`}
            >
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
}
