import type { Metadata } from "next";
import {
    Bebas_Neue,
    Cascadia_Code,
    Cascadia_Mono,
    Geist,
    Geist_Mono,
    JetBrains_Mono,
    Poppins,
    Rubik,
} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ClientLayout from "./layout-client";

// Local Fonts
const helvetica = localFont({
    src: [
        {
            path: "./fonts/Helvetica.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/Helvetica-Bold.ttf",
            weight: "700",
            style: "normal",
        },
        {
            path: "./fonts/Helvetica-Compressed.otf",
            weight: "600",
            style: "normal",
        },
    ],
    variable: "--font-helvetica",
    display: "swap",
});

const helveticaNeue = localFont({
    src: [
        {
            path: "./fonts/HelveticaNeueMedium.otf",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeueBold.otf",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-helvetica-neue",
    display: "swap",
});

// Google Fonts

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    weight: [
        "100", // Thin
        "200", // Extra Light
        "300", // Light
        "400", // Regular
        "500", // Medium
        "600", // Semi Bold
        "700", // Bold
        "800", // Extra Bold
        "900", // Black
    ],
    style: ["normal", "italic"],
    subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
    variable: "--font-bebas",
    weight: [
        "400", // Regular
    ],
    style: ["normal"],
    subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
});

const rubik = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"],
});

const cascadia = Cascadia_Code({
    variable: "--font-cascadia",
    subsets: ["latin"],
});

const cascadiaMono = Cascadia_Mono({
    variable: "--font-cascadia-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Maynkudu",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`
                    ${geistSans.variable} 
                    ${geistMono.variable} 
                    ${poppins.variable} 
                    ${bebasNeue.variable} 
                    ${cascadia.variable}
                    ${cascadiaMono.variable}
                    ${helvetica.variable}
                    ${helveticaNeue.variable} 
                    ${jetBrainsMono.variable}
                    ${rubik.variable}
                    bg-background text-foreground transition-colors duration-500 font-poppins tracking-tighter font-medium`}
            >
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
}
