import ContextMenu from "@/components/menu/ContextMenu";
import Navbar from "@/components/navbar";
import PageTransition from "@/components/transition/PageTransition";
import ThemeTransition from "@/components/transition/ThemeTransition";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased transition-colors duration-500`}>
                <ThemeProvider attribute="class" defaultTheme="light">
                    <ThemeTransition />
                    <PageTransition>
                        <Navbar />
                        <ContextMenu />
                        {children}
                    </PageTransition>
                </ThemeProvider>
            </body>
        </html>
    );
}
